services:
  mukkaebi_db:
    image: mysql:latest
    restart: always
    mem_limit: 256m
    container_name: mysql_vita
    ports:
      - '3306:3306'
    environment: # -e 옵션
      - MYSQL_ROOT_PASSWORD=9240
      - MYSQL_DATABASE=mukkaebi
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - TZ=Asia/Seoul
      - LANG=C.UTF-8
    command: # 명령어 실행
      - --performance_schema=off
      - --innodb-buffer-pool-size=16M
      - --key_buffer_size=16M
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - /usr/local/mysql:/var/lib/mysql # 저장
      - ./initdb.d:/docker-entrypoint-initdb.d
      - .:/app
    working_dir: /app
